- name: BUILD RENDEZVOUS CANDIDATE XML DATA
  template:
    src: rendezvous_candidate.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/rendezvous_candidate.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/rendezvous_candidate.xml"
