- name: BUILD DHCP SNOOPING GLOBAL XML DATA
  template:
    src: dhcp_snoop_global.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/dhcp_snoop_global.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/dhcp_snoop_global.xml"
