- name: BUILD OSPF AUTHENTICATION XML DATA
  template:
    src: ospf_authentication.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/ospf_authentication.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/ospf_authentication.xml"
