- name: BUILD ARP INSPECTION XML DATA
  template:
    src: arp_inspection.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/arp_inspection.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/arp_inspection.xml"
