- name: BUILD LOAD BALANCE ALGORITHM XML DATA
  template:
    src: load_balance_algorithm.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/load_balance_algorithm.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/load_balance_algorithm.xml"
