- name: BUILD CORE UPLINK PORTS XML DATA
  template:
    src: distribution_ports_to_core.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/distribution_ports_to_core.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/distribution_ports_to_core.xml"

- name: BUILD MULTICAST OPTIMIZATION CLI DATA
  template:
    src: multicast_optimization.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/multicast_optimization.cfg"
  when: "model | string in ['6500', '6800']"

- name: PUSH CONFIG TO REMOTES
  ios_config:
    provider: "{{ provider }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/multicast_optimization.cfg"
  when: "model | string in ['6500', '6800']"
