- name: BUILD SYS_PROCESS_SOURCE_IFACE XML DATA
  template:
    src: sys_process_source_iface.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/sys_process_source_iface.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/sys_process_source_iface.xml"
