- name: BUILD VTP LOCAL LOGIN DATA
  template:
    src: local_login.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/local_login.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/local_login.xml"
