- name: BUILD IP_PIM_SPARSE_ACCESS XML DATA
  template:
    src: ip_pim_sparse_access.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/ip_pim_sparse_access.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/ip_pim_sparse_access.xml"
