- name: BUILD RENDEZVOUS MAP XML DATA
  template:
    src: rendezvous_map.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/rendezvous_map.xml"

- name: BUILD RENDEZVOUS DISCOVERY AND ANNOUNCE CLI DATA
  template:
    src: rendezvous_apply_map.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/rendezvous_apply_map.cfg"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/rendezvous_map.xml"
