- name: BUILD LOOPBACK_IP XML DATA
  template:
    src: loopback_ip.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/loopback_ip.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/loopback_ip.xml"
