- name: BUILD NTP XML DATA
  template:
    src: ntp.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/ntp.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/ntp.xml"

# - name: BUILD NTP UPDATE CALENDAR CLI DATA
#   template:
#     src: ntp_calendar.j2
#     dest: "{{ configs_dir }}/{{ inventory_hostname }}/ntp_calendar.cfg"
#   when: "model | string in ['4500', '6500', '6800']"
# 
# - name: PUSH CONFIG TO REMOTES
#   ios_config:
#     provider: "{{ provider }}"
#     save_when: modified
#     src: "{{ configs_dir }}/{{ inventory_hostname }}/ntp_calendar.cfg"
