- name: BUILD UDLD XML DATA
  template:
    src: udld.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/udld.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/udld.xml"
