- name: BUILD SWITCH REDUNDNACY CONFIG XML DATA
  template:
    src: switch_redundancy.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/switch_redundancy.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/switch_redundancy.xml"
