- name: BUILD DNS XML DATA
  template:
    src: dns.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/dns.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/dns.xml"
