- name: BUILD TRUNK_UPLINK XML DATA
  template:
    src: trunk_uplink.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/trunk_uplink.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/trunk_uplink.xml"
