- name: BUILD CORE UPLINK OSPF XML DATA
  template:
    src: distribution_ports_ospf.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/distribution_ports_ospf.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/distribution_ports_ospf.xml"
