- name: BUILD ERRDISABLE XML DATA
  template:
    src: errdisable.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/errdisable.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/errdisable.xml"
