- name: BUILD ANTI-VLAN XML DATA
  template:
    src: anti_vlan_hopping.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/anti_vlan_hopping.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/anti_vlan_hopping.xml"
