- name: BUILD MGMT ACL XML DATA
  template:
    src: mgmt_acl.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/mgmt_acl.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/mgmt_acl.xml"
