- name: BUILD PURGE ROUTE XML DATA
  template:
    src: purge_route.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/purge_route.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/purge_route.xml"
